import { createFileRoute } from "@tanstack/react-router";
import { useState, useMemo } from "react";
import {
  Globe,
  Palette,
  Users,
  MessageSquare,
  Settings,
  Copy,
  Check,
  Sparkles,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { compileUnstructuredBehavioralPrompt } from "@/prompt-engine/behavioralCompiler";
import { compileStructuredDataPromptWithConfig } from "@/prompt-engine/structuredCompiler";
import type { PromptConfiguration, Industry, ToneStyle, ResponseChannel, MissingDataBehavior, ProblemHandlingMode } from "@/prompt-engine/types";

// @ts-ignore - Route path will be auto-generated by TanStack Router plugin
export const Route = createFileRoute("/wiseyak")({
  head: () => ({
    meta: [
      { title: "WiseYak - Dynamic Prompt Engine" },
      { name: "description", content: "Create personalized AI prompts with dynamic configuration." },
    ],
  }),
  component: WiseYakPage,
});

type FormState = {
  configName: string;
  industry: Industry;
  assistantName: string;
  assistantPersona: string;
  targetLanguage: string;
  responseChannel: ResponseChannel;
  domainDescription: string;
  useCaseDescription: string;
  toneStyle: ToneStyle;
  defaultSentences: number;
  maxSentences: number;
  greetings: string;
  midAcks: string;
  problemHandling: ProblemHandlingMode;
  useBullets: boolean;
  preferSimple: boolean;
  avoidJargon: boolean;
  customInstructions: string;
  userPersona: string;
  requiredKeys: string;
  fallbackText: string;
  missingDataBehavior: MissingDataBehavior;
  preventHallucination: boolean;
  blockFinancial: boolean;
  requireGrounding: boolean;
  ragEnabled: boolean;
};

const INDUSTRIES: Industry[] = ["agriculture", "banking", "telecom", "healthcare", "education", "restaurant", "custom"];
const TONES: ToneStyle[] = ["casual-expert", "formal-secure", "empathetic-direct", "friendly-local", "professional-concise"];
const CHANNELS: ResponseChannel[] = ["voice", "text", "chat", "call-center"];
const PROBLEM_MODES: ProblemHandlingMode[] = ["diagnostic-probe", "direct-remediation", "escalation", "educational-explanation"];
const MISSING_DATA_MODES: MissingDataBehavior[] = ["ask-follow-up", "say-not-available", "escalate", "provide-general-guidance-only"];

function buildConfigFromForm(form: FormState): PromptConfiguration {
  return {
    meta: {
      configName: form.configName || "Custom Config",
      industry: form.industry,
      assistantName: form.assistantName || "Assistant",
      assistantPersona: form.assistantPersona,
      targetLanguage: form.targetLanguage || "English",
      responseChannel: form.responseChannel,
      domainDescription: form.domainDescription || "General assistant",
      useCaseDescription: form.useCaseDescription,
    },
    behavioralOptions: {
      toneStyle: form.toneStyle,
      lengthConstraint: {
        unit: "sentences",
        defaultValue: form.defaultSentences,
        maxElaborationValue: form.maxSentences,
        allowUserRequestedElaboration: true,
      },
      greetingPolicy: {
        initialGreetingsAllowed: form.greetings
          .split(",")
          .map((g) => g.trim())
          .filter(Boolean),
        midConversationAcks: form.midAcks
          .split(",")
          .map((m) => m.trim())
          .filter(Boolean),
        allowInitialGreetingOnlyOnce: true,
        allowRepetition: false,
        requireLocalRespectWords: false,
      },
      problemHandlingMode: form.problemHandling,
      answerStyle: {
        useBulletPoints: form.useBullets,
        useMarkdown: true,
        askFollowUpWhenNeeded: form.problemHandling === "diagnostic-probe",
        preferSimpleLanguage: form.preferSimple,
        avoidTechnicalJargon: form.avoidJargon,
      },
      personalization: {
        userPersona: form.userPersona,
        assistantPersona: form.assistantPersona,
      },
      customInstructionBlocks: form.customInstructions
        .split("\n")
        .map((line) => line.trim())
        .filter(Boolean),
    },
    dataMapping: {
      requiredStructuredKeys: form.requiredKeys
        .split(",")
        .map((k) => k.trim())
        .filter(Boolean),
      optionalStructuredKeys: [],
      fallbackTextTemplate: form.fallbackText || "Information not available.",
      missingDataBehavior: form.missingDataBehavior,
    },
    safetyRules: {
      preventHallucination: form.preventHallucination,
      blockFinancialGuessing: form.blockFinancial,
      blockMedicalDiagnosis: false,
      blockLegalClaims: false,
      requireSourceGrounding: form.requireGrounding,
    },
    ragOptions: {
      enabled: form.ragEnabled,
      maxSnippets: 5,
      includeSourceName: true,
      includeConfidenceScore: true,
    },
  };
}

function WiseYakPage() {
  const [copied, setCopied] = useState<string | null>(null);
  const [form, setForm] = useState<FormState>({
    configName: "My Custom Prompt",
    industry: "agriculture",
    assistantName: "WiseYak",
    assistantPersona: "A helpful and knowledgeable assistant",
    targetLanguage: "English",
    responseChannel: "text",
    domainDescription: "Helpful AI assistant",
    useCaseDescription: "General-purpose assistance",
    toneStyle: "friendly-local",
    defaultSentences: 2,
    maxSentences: 5,
    greetings: "Hello, Hi there",
    midAcks: "Got it, Understood, Sure",
    problemHandling: "diagnostic-probe",
    useBullets: false,
    preferSimple: true,
    avoidJargon: true,
    customInstructions: "",
    userPersona: "A curious learner seeking clear answers",
    requiredKeys: "topic, context",
    fallbackText: "I don't have enough information to answer that question.",
    missingDataBehavior: "ask-follow-up",
    preventHallucination: true,
    blockFinancial: false,
    requireGrounding: true,
    ragEnabled: true,
  });

  const config = useMemo(() => buildConfigFromForm(form), [form]);
  const behavioralPrompt = useMemo(() => compileUnstructuredBehavioralPrompt(config), [config]);
  const structuredPrompt = useMemo(
    () =>
      compileStructuredDataPromptWithConfig(
        {
          currentUserMessage: "Help me with this task",
          conversationLogs: [],
          databasePayload: {},
          ragDocuments: [],
        },
        config
      ),
    [config]
  );

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopied(id);
    setTimeout(() => setCopied(null), 2000);
  };

  const updateForm = (key: keyof FormState, value: unknown) => {
    setForm((prev) => ({ ...prev, [key]: value }));
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 p-6">
      <div className="mx-auto max-w-7xl">
        <div className="mb-8 flex items-center gap-3">
          <Sparkles className="h-8 w-8 text-purple-600" />
          <div>
            <h1 className="text-4xl font-bold text-slate-900">WiseYak</h1>
            <p className="text-lg text-slate-600">Dynamic Prompt Configuration Engine</p>
          </div>
        </div>

        <div className="grid gap-6 lg:grid-cols-2">
          {/* Configuration Panel */}
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Globe className="h-5 w-5" />
                  Core Settings
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <Label htmlFor="configName">Configuration Name</Label>
                  <Input
                    id="configName"
                    value={form.configName}
                    onChange={(e) => updateForm("configName", e.target.value)}
                    placeholder="e.g., My Custom Bot"
                  />
                </div>

                <div className="grid gap-4 sm:grid-cols-2">
                  <div>
                    <Label htmlFor="industry">Industry</Label>
                    <Select value={form.industry} onValueChange={(v) => updateForm("industry", v as Industry)}>
                      <SelectTrigger id="industry">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        {INDUSTRIES.map((ind) => (
                          <SelectItem key={ind} value={ind}>
                            {ind.charAt(0).toUpperCase() + ind.slice(1)}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  <div>
                    <Label htmlFor="responseChannel">Response Channel</Label>
                    <Select value={form.responseChannel} onValueChange={(v) => updateForm("responseChannel", v as ResponseChannel)}>
                      <SelectTrigger id="responseChannel">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        {CHANNELS.map((ch) => (
                          <SelectItem key={ch} value={ch}>
                            {ch.charAt(0).toUpperCase() + ch.slice(1)}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div>
                  <Label htmlFor="assistantName">Assistant Name</Label>
                  <Input
                    id="assistantName"
                    value={form.assistantName}
                    onChange={(e) => updateForm("assistantName", e.target.value)}
                    placeholder="e.g., Alex"
                  />
                </div>

                <div>
                  <Label htmlFor="targetLanguage">Target Language</Label>
                  <Input
                    id="targetLanguage"
                    value={form.targetLanguage}
                    onChange={(e) => updateForm("targetLanguage", e.target.value)}
                    placeholder="e.g., English, Nepali"
                  />
                </div>

                <div>
                  <Label htmlFor="domainDescription">Domain Description</Label>
                  <Textarea
                    id="domainDescription"
                    value={form.domainDescription}
                    onChange={(e) => updateForm("domainDescription", e.target.value)}
                    placeholder="Describe the domain or use case"
                    className="h-20"
                  />
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Palette className="h-5 w-5" />
                  Behavioral Settings
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <Label htmlFor="tone">Tone Style</Label>
                  <Select value={form.toneStyle} onValueChange={(v) => updateForm("toneStyle", v as ToneStyle)}>
                    <SelectTrigger id="tone">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {TONES.map((tone) => (
                        <SelectItem key={tone} value={tone}>
                          {tone.split("-").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ")}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="grid gap-4 sm:grid-cols-2">
                  <div>
                    <Label htmlFor="defaultSentences">Default Sentences</Label>
                    <Input
                      id="defaultSentences"
                      type="number"
                      min="1"
                      max="10"
                      value={form.defaultSentences}
                      onChange={(e) => updateForm("defaultSentences", parseInt(e.target.value))}
                    />
                  </div>
                  <div>
                    <Label htmlFor="maxSentences">Max Sentences</Label>
                    <Input
                      id="maxSentences"
                      type="number"
                      min="1"
                      max="20"
                      value={form.maxSentences}
                      onChange={(e) => updateForm("maxSentences", parseInt(e.target.value))}
                    />
                  </div>
                </div>

                <div>
                  <Label htmlFor="greetings">Initial Greetings (comma-separated)</Label>
                  <Input
                    id="greetings"
                    value={form.greetings}
                    onChange={(e) => updateForm("greetings", e.target.value)}
                    placeholder="e.g., Hello, Hi there"
                  />
                </div>

                <div>
                  <Label htmlFor="midAcks">Mid-Conversation Acknowledgments</Label>
                  <Input
                    id="midAcks"
                    value={form.midAcks}
                    onChange={(e) => updateForm("midAcks", e.target.value)}
                    placeholder="e.g., Got it, Understood"
                  />
                </div>

                <div>
                  <Label htmlFor="problemHandling">Problem Handling Mode</Label>
                  <Select
                    value={form.problemHandling}
                    onValueChange={(v) => updateForm("problemHandling", v as ProblemHandlingMode)}
                  >
                    <SelectTrigger id="problemHandling">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {PROBLEM_MODES.map((mode) => (
                        <SelectItem key={mode} value={mode}>
                          {mode.split("-").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ")}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="flex flex-col gap-3">
                  <label className="flex items-center gap-2 text-sm">
                    <input
                      type="checkbox"
                      checked={form.useBullets}
                      onChange={(e) => updateForm("useBullets", e.target.checked)}
                      className="h-4 w-4"
                    />
                    Use bullet points
                  </label>
                  <label className="flex items-center gap-2 text-sm">
                    <input
                      type="checkbox"
                      checked={form.preferSimple}
                      onChange={(e) => updateForm("preferSimple", e.target.checked)}
                      className="h-4 w-4"
                    />
                    Prefer simple language
                  </label>
                  <label className="flex items-center gap-2 text-sm">
                    <input
                      type="checkbox"
                      checked={form.avoidJargon}
                      onChange={(e) => updateForm("avoidJargon", e.target.checked)}
                      className="h-4 w-4"
                    />
                    Avoid technical jargon
                  </label>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Users className="h-5 w-5" />
                  Personalization
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <Label htmlFor="assistantPersona">Assistant Persona</Label>
                  <Textarea
                    id="assistantPersona"
                    value={form.assistantPersona}
                    onChange={(e) => updateForm("assistantPersona", e.target.value)}
                    placeholder="Describe the assistant's personality"
                    className="h-20"
                  />
                </div>

                <div>
                  <Label htmlFor="userPersona">User Persona</Label>
                  <Textarea
                    id="userPersona"
                    value={form.userPersona}
                    onChange={(e) => updateForm("userPersona", e.target.value)}
                    placeholder="Describe the typical user"
                    className="h-20"
                  />
                </div>

                <div>
                  <Label htmlFor="customInstructions">Custom Instructions (one per line)</Label>
                  <Textarea
                    id="customInstructions"
                    value={form.customInstructions}
                    onChange={(e) => updateForm("customInstructions", e.target.value)}
                    placeholder="Add any custom behavior rules"
                    className="h-24"
                  />
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Settings className="h-5 w-5" />
                  Safety & Data
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <Label htmlFor="requiredKeys">Required Data Keys (comma-separated)</Label>
                  <Input
                    id="requiredKeys"
                    value={form.requiredKeys}
                    onChange={(e) => updateForm("requiredKeys", e.target.value)}
                    placeholder="e.g., user_id, context"
                  />
                </div>

                <div>
                  <Label htmlFor="fallbackText">Fallback Text</Label>
                  <Textarea
                    id="fallbackText"
                    value={form.fallbackText}
                    onChange={(e) => updateForm("fallbackText", e.target.value)}
                    placeholder="Response when data is missing"
                    className="h-20"
                  />
                </div>

                <div>
                  <Label htmlFor="missingDataBehavior">Missing Data Behavior</Label>
                  <Select
                    value={form.missingDataBehavior}
                    onValueChange={(v) => updateForm("missingDataBehavior", v as MissingDataBehavior)}
                  >
                    <SelectTrigger id="missingDataBehavior">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {MISSING_DATA_MODES.map((mode) => (
                        <SelectItem key={mode} value={mode}>
                          {mode.split("-").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ")}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="flex flex-col gap-3">
                  <label className="flex items-center gap-2 text-sm">
                    <input
                      type="checkbox"
                      checked={form.preventHallucination}
                      onChange={(e) => updateForm("preventHallucination", e.target.checked)}
                      className="h-4 w-4"
                    />
                    Prevent hallucination
                  </label>
                  <label className="flex items-center gap-2 text-sm">
                    <input
                      type="checkbox"
                      checked={form.blockFinancial}
                      onChange={(e) => updateForm("blockFinancial", e.target.checked)}
                      className="h-4 w-4"
                    />
                    Block financial guessing
                  </label>
                  <label className="flex items-center gap-2 text-sm">
                    <input
                      type="checkbox"
                      checked={form.requireGrounding}
                      onChange={(e) => updateForm("requireGrounding", e.target.checked)}
                      className="h-4 w-4"
                    />
                    Require source grounding
                  </label>
                  <label className="flex items-center gap-2 text-sm">
                    <input
                      type="checkbox"
                      checked={form.ragEnabled}
                      onChange={(e) => updateForm("ragEnabled", e.target.checked)}
                      className="h-4 w-4"
                    />
                    Enable RAG
                  </label>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Generated Prompts Preview */}
          <div className="space-y-6">
            <Card className="sticky top-6">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <MessageSquare className="h-5 w-5" />
                  Configuration Summary
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex flex-wrap gap-2">
                  <Badge variant="outline">{form.industry}</Badge>
                  <Badge variant="outline">{form.responseChannel}</Badge>
                  <Badge variant="outline">{form.toneStyle}</Badge>
                </div>
                <div className="space-y-2 text-sm">
                  <p>
                    <span className="font-semibold">Name:</span> {form.configName}
                  </p>
                  <p>
                    <span className="font-semibold">Assistant:</span> {form.assistantName}
                  </p>
                  <p>
                    <span className="font-semibold">Language:</span> {form.targetLanguage}
                  </p>
                  <p>
                    <span className="font-semibold">Length:</span> {form.defaultSentences} sentences (max {form.maxSentences})
                  </p>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Compiled Prompts</CardTitle>
                <CardDescription>Live preview of generated system and data prompts</CardDescription>
              </CardHeader>
              <CardContent>
                <Tabs defaultValue="behavioral" className="w-full">
                  <TabsList className="grid w-full grid-cols-2">
                    <TabsTrigger value="behavioral">Behavioral</TabsTrigger>
                    <TabsTrigger value="structured">Structured Data</TabsTrigger>
                  </TabsList>

                  <TabsContent value="behavioral" className="space-y-3">
                    <div className="max-h-96 overflow-y-auto rounded-lg border border-slate-200 bg-slate-50 p-4 font-mono text-xs text-slate-700">
                      <pre className="whitespace-pre-wrap break-words">{behavioralPrompt}</pre>
                    </div>
                    <Button
                      size="sm"
                      variant="outline"
                      className="w-full"
                      onClick={() => copyToClipboard(behavioralPrompt, "behavioral")}
                    >
                      {copied === "behavioral" ? (
                        <>
                          <Check className="mr-2 h-4 w-4" />
                          Copied!
                        </>
                      ) : (
                        <>
                          <Copy className="mr-2 h-4 w-4" />
                          Copy Prompt
                        </>
                      )}
                    </Button>
                  </TabsContent>

                  <TabsContent value="structured" className="space-y-3">
                    <div className="max-h-96 overflow-y-auto rounded-lg border border-slate-200 bg-slate-50 p-4 font-mono text-xs text-slate-700">
                      <pre className="whitespace-pre-wrap break-words">{structuredPrompt}</pre>
                    </div>
                    <Button
                      size="sm"
                      variant="outline"
                      className="w-full"
                      onClick={() => copyToClipboard(structuredPrompt, "structured")}
                    >
                      {copied === "structured" ? (
                        <>
                          <Check className="mr-2 h-4 w-4" />
                          Copied!
                        </>
                      ) : (
                        <>
                          <Copy className="mr-2 h-4 w-4" />
                          Copy Prompt
                        </>
                      )}
                    </Button>
                  </TabsContent>
                </Tabs>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}
